name: Github actions mavan build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - name:  checkout step1 main branch from github
      - uses: actions/checkout@v2
      - name : step2-setup JDK 11
      - uses:  actions/setup-java@v2
        with :
         java-version: 11
      - name: step-3 Github actions mavan build project
        run: mvn -b package --file pom.xml 
